import './globals.css'
import { Poppins } from 'next/font/google'
import { AppProvider } from "@/app/Context/AppContext"
import PageTransition from "@/app/components/PageTransition";



const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata = {
  title: 'SiteScannerPro',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body
        style={{
          margin: 0,
          position: "relative", // needed for motion div
          minHeight: "100vh",
          backgroundColor: "#E0DAD0", 
          overflowX: "hidden",
        }}
      >
        <AppProvider>
          <PageTransition direction="right">
            {children}
          </PageTransition>
        </AppProvider>
      </body>
    </html>

  )
}
